services:
  - type: web
    name: whatsfinance
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn whatsfinance.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
